language: python
python:
  - "3.7.9"

before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python -m pytest -m "not stress"
