# put this file in custom input dir or in ~/.config/automlbenchmark directory
# in order to have a custom setup, allowing to add custom frameworks definitions (in our case, creating a benchmark for various H2O versions)
---
project_repository: https://github.com/openml/automlbenchmark

frameworks:
  definition_file:
    - '{root}/resources/frameworks.yaml'
    - '{user}/frameworks.yaml'

benchmarks:
  definition_dir:
    - '{user}'
    - '{root}/resources/benchmarks'
  defaults:
    cores: 2

aws:
  iam:
    temporary: false

  s3:
    temporary: false
  
  ec2:
  #  instance_type: c5.xlarge
    instance_type: t3.small

  resource_files:
    - '{user}/config.yaml'
    - '{user}/frameworks.yaml'
    - '{user}/Decision_Tree'

  use_docker: false


