name: Run `runbenchmark.py`

on:
  workflow_dispatch:
    inputs:
      python_version:
        default: '3.9'
      os:
        default: 'ubuntu-latest'
      framework:
        default: 'randomforest'
      options:
        default: ''

jobs:
  run_benchmark:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Runs on ${{ inputs.os }}
        run: echo Preparing to benchmark ${{ inputs.framework }} ${{ inputs.options }}
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Install Py${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install benchmark dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install ${{ inputs.framework }}
        run: python runbenchmark.py ${{ inputs.framework }} -s only
        env:
          GITHUB_PAT: ${{ secrets.PUBLIC_ACCESS_GITHUB_PAT }}
      - name: Benchmark ${{ inputs.framework }}
        run: python runbenchmark.py ${{ inputs.framework }} ${{ inputs.options }}
