name: Tag with Stable

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  tag-if-latest-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag and add stable tag if highest version
        run: ./.github/scripts/tag-set.sh $GITHUB_REF push
