name: Version Bump

on:
  release:
    types:
      - published

  workflow_dispatch:

env:
  BRANCH: ${{ github.event.release.target_commitish }}
  TAG: ${{ github.event.release.tag_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      - name: Bump version from tag
        run: ./.github/scripts/version-set.sh $TAG push
      - name: Update tag
        run: ./.github/scripts/tag-set.sh $TAG push
      - name: Restore dev version
        run: ./.github/scripts/version-set.sh "" push
