name: Version Bump

on:
  release:
    types:
      - created

  workflow_dispatch:

env:
  BRANCH: ${{ github.event.release.target_commitish }}
  TAG: ${{ github.event.release.tag_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
      - name: Bump version from tag
        run: |
          VERSION=$(echo $TAG | sed 's/^v//')
          PLACEHOLDER='__version__ = _dev_version'
          VERSION_FILE='amlb/__version__.py'
          grep "$PLACEHOLDER" "$VERSION_FILE"
          sed -i "s/$PLACEHOLDER/__version__ = \"${VERSION}\"/g" "$VERSION_FILE"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash
      - name: Commit version changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update version to $VERSION"
      - name: Update tag
        run: |
          git tag $TAG
          git push
          git push --tags -f

