name: Version Bump

on:
  release:
    types:
      - published

  workflow_dispatch:

env:
  BRANCH: ${{ github.event.release.target_commitish }}
  TAG: ${{ github.event.release.tag_name }}

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Release only from stable-v* branch
        if: ${{ !startsWith(env.BRANCH, 'stable-v') }}
        uses: actions/github-script@v6
        with:
          script: core.setFailed("Releases can only be made from 'stable-v*' branches")
  rollback:
    needs: validation
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Rollback if invalid release
        uses: author/action-rollback@stable
        with:
          tag: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  versioning:
    needs: validation
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      - name: Bump version from tag
        run: ./.github/scripts/version-set.sh $TAG push
      - name: Update tag
        run: ./.github/scripts/tag-set.sh $TAG push
      - name: Restore dev version
        run: ./.github/scripts/version-set.sh "" push
